

## 请自行修改下面信息

spring:
  application:
    name: shiro-jwt-applet
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update      # 请自行修改 请自行修改 请自行修改
    open-in-view: false     # 关闭 OSIV

#  datasource本地配置
  datasource:
    url: jdbc:mysql://localhost:3306/shopping?characterEncoding=utf-8
    username: root
    password: 123456@cc
    driver-class-name: com.mysql.jdbc.Driver

#  redis本地配置 请自行配置
  redis:
    database: 0
    host: localhost
    port: 6379
server:
  port: 443
  tomcat:
    max-connections: 800
    accept-count: 30000
    min-spare-threads: 20
  ssl:
    key-store: xxxxxxxxxxxxxxxxx
    key-store-password: xxxxxxxxxxxxxxxxxx
    key-store-type: PKCS12
    enabled: true


#  微信小程序配置 appid /appsecret
wx:
  applet:
    appid: xxxxxxxxxxxxxxx
    appsecret: xxxxxxxxxxxxxxxxxxxx
